### ISSUE TITLE
What is diffBy 's default?

### ISSUE THREAD

**Issue by knakayama** [nickpisacane/websync#2]
It seems that `diffBy` default is [size](https://github.com/nickpisacane/websync/blob/master/src/Websync.ts#L71), not `modtime` . Are [the doc](https://github.com/nickpisacane/websync#options) and [help](https://github.com/nickpisacane/websync/blob/master/src/cli.ts#L19) correct?

Anyway, thanks for your useful tool!

**Comment by nickpisacane** [comment]
Great catch! It's supposed to be `modtime`. That's the default in [diff.ts](https://github.com/nickpisacane/websync/blob/master/src/diff.ts#L23), but not in [Websync.ts](https://github.com/nickpisacane/websync/blob/master/src/Websync.ts#L71). Will update and patch. Glad you are making use of it, and thanks for the find!

**Comment by nickpisacane** [comment]
Updated on version 0.0.13!
